name: whats_new_feature
description: Show apple like whats new feature in the latest update
version: 0.0.1+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^1.4.2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^2.4.0